// ============================================================
// mockData.js — 20 Ovejas Guerreras Black Sheeps
// char-01 (Alex) reservado para Super Admin.
// chars 02-20 disponibles para asesores al registrarse.
// En producción con Supabase, este archivo actúa solo como fallback de demo.
// ============================================================

export const MOCK_CHARACTERS = [
  // ── Personajes Originales 1-10 ──────────────────────────────
  {
    id: 'char-01', slug: '01_sheep_alex',
    name: 'Alex (The Golden Closer)',
    archetype: 'Líder / Trofeo de Oro',
    avatar_url: '/characters/01_sheep_alex/avatar.png',
    card_url: '/characters/01_sheep_alex/card.png',
    fullbody_url: '/characters/01_sheep_alex/fullbody.png',
    is_assigned: true, assigned_to_user_id: 'user-01',
  },
  {
    id: 'char-02', slug: '02_sheep_sofia',
    name: 'Sofía (The Mystic Dealmaker)',
    archetype: 'Estratega / Capa Púrpura',
    avatar_url: '/characters/02_sheep_sofia/avatar.png',
    card_url: '/characters/02_sheep_sofia/card.png',
    fullbody_url: '/characters/02_sheep_sofia/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-03', slug: '03_sheep_diego',
    name: 'Diego (The Cyber Hunter)',
    archetype: 'Cazador / Visor Cian',
    avatar_url: '/characters/03_sheep_diego/avatar.png',
    card_url: '/characters/03_sheep_diego/card.png',
    fullbody_url: '/characters/03_sheep_diego/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-04', slug: '04_sheep_valeria',
    name: 'Valeria (The Neon Valkyrie)',
    archetype: 'Guerrera Aérea / Alas Fucsia',
    avatar_url: '/characters/04_sheep_valeria/avatar.png',
    card_url: '/characters/04_sheep_valeria/card.png',
    fullbody_url: '/characters/04_sheep_valeria/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-05', slug: '05_sheep_marcos',
    name: 'Marcos (The Iron Ram)',
    archetype: 'Fuerza Bruta / Cuernos de Hierro',
    avatar_url: '/characters/05_sheep_marcos/avatar.png',
    card_url: '/characters/05_sheep_marcos/card.png',
    fullbody_url: '/characters/05_sheep_marcos/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-06', slug: '06_sheep_elena',
    name: 'Elena (The Diamond Queen)',
    archetype: 'Monarca / Tiara Diamante',
    avatar_url: '/characters/06_sheep_elena/avatar.png',
    card_url: '/characters/06_sheep_elena/card.png',
    fullbody_url: '/characters/06_sheep_elena/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-07', slug: '07_sheep_javier',
    name: 'Javier (The Thunder Striker)',
    archetype: 'Velocista / Plasma Eléctrico',
    avatar_url: '/characters/07_sheep_javier/avatar.png',
    card_url: '/characters/07_sheep_javier/card.png',
    fullbody_url: '/characters/07_sheep_javier/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-08', slug: '08_sheep_mateo',
    name: 'Mateo (The Shadow Rogue)',
    archetype: 'Sigilo / Capucha Carmesí',
    avatar_url: '/characters/08_sheep_mateo/avatar.png',
    card_url: '/characters/08_sheep_mateo/card.png',
    fullbody_url: '/characters/08_sheep_mateo/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-09', slug: '09_sheep_camila',
    name: 'Camila (The Flame Empress)',
    archetype: 'Fuego Volcánico / Magma',
    avatar_url: '/characters/09_sheep_camila/avatar.png',
    card_url: '/characters/09_sheep_camila/card.png',
    fullbody_url: '/characters/09_sheep_camila/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-10', slug: '10_sheep_lucas',
    name: 'Lucas (The Titan Vanguard)',
    archetype: 'Tanque / Escudo Obsidiana',
    avatar_url: '/characters/10_sheep_lucas/avatar.png',
    card_url: '/characters/10_sheep_lucas/card.png',
    fullbody_url: '/characters/10_sheep_lucas/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  // ── Nuevos Personajes 11-20 — Diseño Único ──────────────────
  {
    id: 'char-11', slug: '11_sheep_rio',
    name: 'Río (The Storm Admiral)',
    archetype: 'Almirante / Parche de Capitán + Capa Tormenta',
    avatar_url: '/characters/11_sheep_rio/avatar.png',
    card_url: '/characters/11_sheep_rio/card.png',
    fullbody_url: '/characters/11_sheep_rio/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-12', slug: '12_sheep_luna',
    name: 'Luna (The Void Sorceress)',
    archetype: 'Maga del Vacío / Mohawk Violeta + Constelaciones',
    avatar_url: '/characters/12_sheep_luna/avatar.png',
    card_url: '/characters/12_sheep_luna/card.png',
    fullbody_url: '/characters/12_sheep_luna/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-13', slug: '13_sheep_axel',
    name: 'Axel (The Inferno Berserker)',
    archetype: 'Berserker / Armadura de Lava + Cicatriz de Guerra',
    avatar_url: '/characters/13_sheep_axel/avatar.png',
    card_url: '/characters/13_sheep_axel/card.png',
    fullbody_url: '/characters/13_sheep_axel/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-14', slug: '14_sheep_zara',
    name: 'Zara (The Crystal Archer)',
    archetype: 'Arquera / Orejas Largas + Arco de Cristal',
    avatar_url: '/characters/14_sheep_zara/avatar.png',
    card_url: '/characters/14_sheep_zara/card.png',
    fullbody_url: '/characters/14_sheep_zara/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-15', slug: '15_sheep_rex',
    name: 'Rex (The Omega Juggernaut)',
    archetype: 'Juggernaut / Cuernos Rúnicos + Armadura Negra-Oro',
    avatar_url: '/characters/15_sheep_rex/avatar.png',
    card_url: '/characters/15_sheep_rex/card.png',
    fullbody_url: '/characters/15_sheep_rex/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-16', slug: '16_sheep_nova',
    name: 'Nova (The Starfire Paladin)',
    archetype: 'Paladín / Halo Dorado + Alas de Luz',
    avatar_url: '/characters/16_sheep_nova/avatar.png',
    card_url: '/characters/16_sheep_nova/card.png',
    fullbody_url: '/characters/16_sheep_nova/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-17', slug: '17_sheep_dante',
    name: 'Dante (The Blood Reaver)',
    archetype: 'Asesino / Monóculo Rubí + Tatuaje Tribal',
    avatar_url: '/characters/17_sheep_dante/avatar.png',
    card_url: '/characters/17_sheep_dante/card.png',
    fullbody_url: '/characters/17_sheep_dante/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-18', slug: '18_sheep_iris',
    name: 'Iris (The Prismatic Dancer)',
    archetype: 'Bailarina / Ojos Heterocromía + Cintas Arcoíris',
    avatar_url: '/characters/18_sheep_iris/avatar.png',
    card_url: '/characters/18_sheep_iris/card.png',
    fullbody_url: '/characters/18_sheep_iris/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-19', slug: '19_sheep_kane',
    name: 'Kane (The Iron Sentinel)',
    archetype: 'Guardián / Gafas Metálicas + Escudo Obsidiana',
    avatar_url: '/characters/19_sheep_kane/avatar.png',
    card_url: '/characters/19_sheep_kane/card.png',
    fullbody_url: '/characters/19_sheep_kane/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
  {
    id: 'char-20', slug: '20_sheep_vera',
    name: 'Vera (The Phantom Empress)',
    archetype: 'Emperatriz Fantasma / Ojos Blancos + Niebla Espectral',
    avatar_url: '/characters/20_sheep_vera/avatar.png',
    card_url: '/characters/20_sheep_vera/card.png',
    fullbody_url: '/characters/20_sheep_vera/fullbody.png',
    is_assigned: false, assigned_to_user_id: null,
  },
];

// ── Demo Users (solo Edgardo tiene personaje asignado) ────────
// Los demás asesores de demo no bloquean personajes
export const MOCK_USERS = [
  {
    id: 'user-01',
    name: 'Edgardo Alfonso Rangel',
    email: 'edgardorc8@gmail.com',
    discord_id: '100000000000000001',
    discord_tag: '@edgardorc8',
    country: '🇻🇪 Venezuela',
    role: 'super_admin',
    is_verified: true,
    character_id: 'char-01',
    custom_character_name: 'The Golden Closer',
    battle_cry: '¡Trato cerrado, la manada no perdona!',
    total_sales: 124500.00,
    daily_sales: 15000.00,
    weekly_sales: 42000.00,
    monthly_sales: 124500.00,
    sales_count: 68,
    recent_sales: [
      { amount: 25000, time: 'Hoy, 11:20 AM' },
      { amount: 5000, time: 'Ayer, 4:15 PM' },
      { amount: 25000, time: '17 Sep, 2:30 PM' },
    ],
  },
  {
    id: 'user-02',
    name: 'Ana Gómez',
    email: 'ana@dtodosales.com',
    discord_id: '100000000000000002',
    discord_tag: '@ana_sales',
    country: '🇦🇷 Argentina',
    role: 'admin',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 98200.00,
    daily_sales: 10000.00,
    weekly_sales: 31000.00,
    monthly_sales: 98200.00,
    sales_count: 54,
    recent_sales: [
      { amount: 5000, time: 'Hoy, 10:10 AM' },
      { amount: 5000, time: 'Ayer, 6:00 PM' },
    ],
  },
  {
    id: 'user-03',
    name: 'Diego Ruiz',
    email: 'diego@dtodosales.com',
    discord_id: '100000000000000003',
    discord_tag: '@diego_vip',
    country: '🇲🇽 México',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 76400.00,
    daily_sales: 5000.00,
    weekly_sales: 22000.00,
    monthly_sales: 76400.00,
    sales_count: 42,
    recent_sales: [
      { amount: 25000, time: '18 Sep, 1:40 PM' },
    ],
  },
  {
    id: 'user-04',
    name: 'Valeria Castillo',
    email: 'valeria@dtodosales.com',
    discord_id: '100000000000000004',
    discord_tag: '@vale_closer',
    country: '🇨🇱 Chile',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 58900.00,
    daily_sales: 0,
    weekly_sales: 18000.00,
    monthly_sales: 58900.00,
    sales_count: 31,
    recent_sales: [],
  },
  {
    id: 'user-05',
    name: 'Marcos Varela',
    email: 'marcos@dtodosales.com',
    discord_id: '100000000000000005',
    discord_tag: '@marcos_v',
    country: '🇨🇱 Chile',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 44200.00,
    daily_sales: 5000.00,
    weekly_sales: 14000.00,
    monthly_sales: 44200.00,
    sales_count: 25,
    recent_sales: [],
  },
  {
    id: 'user-06',
    name: 'Elena Peña',
    email: 'elena@dtodosales.com',
    discord_id: '100000000000000006',
    discord_tag: '@elena_deals',
    country: '🇵🇪 Perú',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 39500.00,
    daily_sales: 0,
    weekly_sales: 9000.00,
    monthly_sales: 39500.00,
    sales_count: 21,
    recent_sales: [],
  },
  {
    id: 'user-07',
    name: 'Javier López',
    email: 'javier@dtodosales.com',
    discord_id: '100000000000000007',
    discord_tag: '@javi_sales',
    country: '🇺🇸 USA',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 31200.00,
    daily_sales: 0,
    weekly_sales: 5000.00,
    monthly_sales: 31200.00,
    sales_count: 18,
    recent_sales: [],
  },
  {
    id: 'user-08',
    name: 'Mateo Silva',
    email: 'mateo@dtodosales.com',
    discord_id: '100000000000000008',
    discord_tag: '@mateo_rogue',
    country: '🇨🇴 Colombia',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 24800.00,
    daily_sales: 0,
    weekly_sales: 5000.00,
    monthly_sales: 24800.00,
    sales_count: 14,
    recent_sales: [],
  },
  {
    id: 'user-09',
    name: 'Camila Rojas',
    email: 'camila@dtodosales.com',
    discord_id: '100000000000000009',
    discord_tag: '@camila_flame',
    country: '🇲🇽 México',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 18500.00,
    daily_sales: 0,
    weekly_sales: 2500.00,
    monthly_sales: 18500.00,
    sales_count: 10,
    recent_sales: [],
  },
  {
    id: 'user-10',
    name: 'Lucas Benítez',
    email: 'lucas@dtodosales.com',
    discord_id: '100000000000000010',
    discord_tag: '@lucas_vanguard',
    country: '🇪🇸 España',
    role: 'sales_agent',
    is_verified: true,
    character_id: null,
    custom_character_name: null,
    battle_cry: null,
    total_sales: 12000.00,
    daily_sales: 0,
    weekly_sales: 0,
    monthly_sales: 12000.00,
    sales_count: 7,
    recent_sales: [],
  },
];

export const MOCK_CURRENT_USER = MOCK_USERS[0]; // Edgardo Alfonso Rangel
